image:
  name: python:3.7

release-dev: &release-dev
  step:
    name: Release development version
    trigger: manual
    script:
      - pip install semversioner
      - VERSION=$(semversioner current-version).${BITBUCKET_BUILD_NUMBER}-dev
      - pipe: docker://bitbucketpipelines/bitbucket-pipe-release:3.2.2
        variables:
          DOCKERHUB_USERNAME: $DOCKERHUB_USERNAME
          DOCKERHUB_PASSWORD: $DOCKERHUB_PASSWORD
          IMAGE: luongvo/$BITBUCKET_REPO_SLUG
          GIT_PUSH: 'false'
          VERSION: ${VERSION}
    services:
      - docker


lint: &lint
  step:
      name: Lint the Dockerfile
      image: hadolint/hadolint:latest-debian
      script:
        - hadolint Dockerfile


push: &push
  step:
    script:
      - pipe: docker://bitbucketpipelines/bitbucket-pipe-release:3.2.2
        variables:
          DOCKERHUB_USERNAME: $DOCKERHUB_USERNAME
          DOCKERHUB_PASSWORD: $DOCKERHUB_PASSWORD
          IMAGE: luongvo/$BITBUCKET_REPO_SLUG
    services:
      - docker


pipelines:
  default:
  - <<: *lint
  - <<: *release-dev
  branches:
    master:
    - <<: *lint
    - <<: *push
